const basePath = process.env.NODE_ENV === "production" ? "/my-acad-tutor" : "";
function withBasePath(href: string) { if (href === "/") return `${basePath}/`; if (href.startsWith("#") || href.startsWith("http") || href.startsWith("mailto:")) return href; const cleanHref = href.endsWith("/") ? href.slice(0, -1) : href; return `${basePath}${cleanHref}/`; }

const services = [
  { number: "01", title: "Statistics support", description: "Guidance with probability, descriptive statistics, inference, hypothesis testing, regression, assumptions and interpretation.", examples: ["Statistical concepts", "Method choice", "Assumptions", "Exam revision"] },
  { number: "02", title: "Biostatistics & medical statistics", description: "Support for students and researchers working with health data, epidemiology, survival analysis and clinical research methods.", examples: ["Survival analysis", "Epidemiological measures", "Clinical trials", "Health data"] },
  { number: "03", title: "Programming & statistical software", description: "Guidance with R, Python, SPSS, SAS and Stata for academic analysis, debugging and reproducible workflows.", examples: ["Code walkthroughs", "Debugging", "Data cleaning", "Reproducible structure"] },
  { number: "04", title: "Dissertation and research support", description: "Structured guidance for research questions, study design, variables, analysis strategy, interpretation and limitations.", examples: ["Research questions", "Variable planning", "Analysis strategy", "Reporting"] },
  { number: "05", title: "Data science and machine learning", description: "Support with data preparation, visualisation, prediction modelling, validation, performance metrics and responsible reporting.", examples: ["Prediction vs inference", "Validation", "Performance metrics", "ML foundations"] },
  { number: "06", title: "Bioinformatics and omics", description: "Guidance with biological data analysis concepts, omics workflows, gene expression and interpretation of results.", examples: ["RNA-seq foundations", "Omics interpretation", "Workflow planning", "Biological meaning"] },
];

const supportTypes = ["Concept explanation", "Method selection", "Software walkthroughs", "Interpretation support", "Revision planning", "Research project guidance", "Tables and figures", "Academic reporting"];

export default function ServicesPage() {
  return (<main className="min-h-screen bg-[#f7f4ee] px-5 py-10 text-[#111111] md:px-8 md:py-20"><section className="mx-auto max-w-7xl"><a href={withBasePath("/")} className="text-sm font-bold text-[#8b1116] hover:text-[#5f0b0f]">← Back to homepage</a>
    <section className="mt-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-10 lg:p-12"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Services</p><div className="mt-5 grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-end"><div><h1 className="max-w-5xl font-sans text-4xl font-black leading-[1.02] tracking-[-0.055em] sm:text-5xl md:text-7xl">Academic support for quantitative learning and research.</h1><p className="mt-6 max-w-4xl text-base leading-8 text-neutral-700 md:text-lg md:leading-9">Guidance-based support across statistics, biostatistics, programming, data science, bioinformatics and research methods.</p></div><div className="rounded-[1.75rem] border border-[#ead8d8] bg-[#f7f4ee] p-6"><p className="text-sm font-black uppercase tracking-[0.2em] text-[#8b1116]">What support means</p><h2 className="mt-4 font-sans text-2xl font-black tracking-[-0.04em]">Guidance, explanation and academic confidence.</h2><p className="mt-4 text-sm leading-7 text-neutral-700">Support helps you understand concepts, plan analysis, review assumptions, interpret results and develop a clearer academic workflow.</p></div></div></section>
    <section className="mt-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Support areas</p><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => (<article key={service.title} className="rounded-[2rem] border border-neutral-200 bg-[#f7f4ee] p-6"><div className="flex items-start justify-between gap-4"><p className="font-sans text-4xl font-black tracking-[-0.05em] text-[#8b1116]">{service.number}</p><span className="rounded-full bg-white px-3 py-1 text-xs font-black uppercase tracking-[0.16em] text-neutral-600">Support</span></div><h2 className="mt-5 font-sans text-2xl font-black leading-tight tracking-[-0.04em]">{service.title}</h2><p className="mt-4 text-sm leading-7 text-neutral-700">{service.description}</p><div className="mt-5 grid gap-2">{service.examples.map((item) => (<div key={item} className="rounded-2xl border border-neutral-200 bg-white px-4 py-3 text-sm font-bold leading-6 text-neutral-800">{item}</div>))}</div></article>))}</div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[0.95fr_1.05fr]"><article className="rounded-[2rem] border border-neutral-200 bg-[#111111] p-6 text-white shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/85">Academic integrity</p><h2 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Support is guidance-based.</h2><p className="mt-5 text-base leading-8 text-white/90">We help students understand concepts, software, methods and interpretation. We do not complete assessed work or support misconduct.</p><a href={withBasePath("/academic-integrity")} className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-[#111111]">Read academic integrity policy →</a></article><article className="rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Types of help</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{supportTypes.map((type) => (<div key={type} className="rounded-2xl border border-neutral-200 bg-[#f7f4ee] px-4 py-3 text-sm font-bold leading-6 text-neutral-800">{type}</div>))}</div></article></section>
    <section className="mt-8 rounded-[2rem] bg-[#8b1116] p-6 text-white shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/90">Request support</p><div className="mt-4 grid gap-8 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><h2 className="max-w-3xl font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Send your subject, topic and learning goal.</h2><p className="mt-5 max-w-3xl text-base leading-8 text-white/80">Include your academic level, topic, software if relevant, deadline and what you need help understanding.</p></div><div className="grid gap-3"><a href={withBasePath("/contact")} className="rounded-full bg-white px-6 py-4 text-center text-sm font-black text-[#111111]">Submit an enquiry</a><a href={withBasePath("/courses")} className="rounded-full border border-white/25 bg-white/10 px-6 py-4 text-center text-sm font-black text-white">View courses</a></div></div></section>
  </section></main>);
}
