import NormalDistributionExplorer from "@/components/interactive/NormalDistributionExplorer";
import RegressionLineExplorer from "@/components/interactive/RegressionLineExplorer";
import ConfidenceIntervalSimulator from "@/components/interactive/ConfidenceIntervalSimulator";

const basePath = process.env.NODE_ENV === "production" ? "/my-acad-tutor" : "";
function withBasePath(href: string) { if (href === "/") return `${basePath}/`; if (href.startsWith("#") || href.startsWith("http") || href.startsWith("mailto:")) return href; const cleanHref = href.endsWith("/") ? href.slice(0, -1) : href; return `${basePath}${cleanHref}/`; }

const pathways = [
  { number: "01", title: "Statistics Foundation", tag: "Available", level: "Beginner to intermediate", href: "/courses/statistics-foundation", description: "A theory-first, zero-coding pathway that builds statistical thinking from the beginning.", details: ["5 modules and structured lessons", "Lectures, notes, labs, examples and quizzes", "Designed before biostatistics and data science"], outcomes: ["Understand notation", "Build probability confidence", "Interpret inference carefully"], cta: "Open pathway" },
  { number: "02", title: "Machine Learning in Biostatistics", tag: "Module 1 available", level: "Intermediate", href: "/courses/machine-learning-biostatistics", description: "A medical machine learning pathway focused on prediction, validation, leakage and reporting.", details: ["Module 1 foundations available", "Health-data examples", "Validation and clinical interpretation"], outcomes: ["Understand prediction modelling", "Recognise overfitting", "Interpret metrics clinically"], cta: "View pathway" },
  { number: "03", title: "Research Methods & Data Analysis", tag: "Planned", level: "Project support", href: "/courses", description: "A future applied pathway for dissertations, research reports and analysis planning.", details: ["Study design", "Analysis strategy", "Limitations and reporting"], outcomes: ["Plan analysis", "Choose methods", "Report responsibly"], cta: "Explore courses" },
];

const resourceHighlights = [
  { title: "Choosing the correct statistical test", href: "/resources/how-to-choose-the-correct-statistical-test" },
  { title: "P-values, confidence intervals and effect sizes", href: "/resources/understanding-p-values-confidence-intervals-and-effect-sizes" },
  { title: "Linear regression assumptions and diagnostics", href: "/resources/linear-regression-assumptions-and-diagnostics" },
  { title: "Survival analysis: Kaplan-Meier curves and Cox regression", href: "/resources/survival-analysis-kaplan-meier-curves-and-cox-regression" },
  { title: "R, Python, SPSS, SAS or Stata: which should I use?", href: "/resources/r-python-spss-sas-stata-which-should-i-use" },
];

export default function LearningHubPage() { return (<main className="min-h-screen bg-[#f7f4ee] px-5 py-10 text-[#111111] md:px-8 md:py-20"><section className="mx-auto max-w-7xl"><a href={withBasePath("/")} className="text-sm font-bold text-[#8b1116] hover:text-[#5f0b0f]">← Back to homepage</a>
<section className="mt-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-10 lg:p-12"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Learning Hub</p><div className="mt-5 grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-end"><div><h1 className="max-w-5xl font-sans text-4xl font-black leading-[1.02] tracking-[-0.055em] sm:text-5xl md:text-7xl">Learn quantitative subjects through structured pathways.</h1><p className="mt-6 max-w-4xl text-base leading-8 text-neutral-700 md:text-lg md:leading-9">The Learning Hub brings together guided courses, interactive demos, flagship resources and platform previews for statistics, biostatistics, data science and research methods.</p></div><div className="rounded-[1.75rem] border border-[#ead8d8] bg-[#f7f4ee] p-6"><p className="text-sm font-black uppercase tracking-[0.2em] text-[#8b1116]">How to use the hub</p><div className="mt-5 grid gap-3">{["Choose a pathway", "Follow the sequence", "Use active practice", "Return to theory"].map((step, index) => (<div key={step} className="rounded-3xl border border-neutral-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#8b1116]">Step {index + 1}</p><h2 className="mt-2 font-sans text-lg font-black tracking-[-0.03em]">{step}</h2></div>))}</div></div></div><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><a href="#pathways" className="inline-flex w-full items-center justify-center rounded-full bg-[#111111] px-6 py-4 text-sm font-black text-white sm:w-auto">View pathways</a><a href={withBasePath("/interactive-demos")} className="inline-flex w-full items-center justify-center rounded-full border border-neutral-300 px-6 py-4 text-sm font-black text-[#111111] sm:w-auto">Try demos</a><a href={withBasePath("/resources")} className="inline-flex w-full items-center justify-center rounded-full border border-neutral-300 px-6 py-4 text-sm font-black text-[#111111] sm:w-auto">Browse resources</a></div></section>
<section id="pathways" className="mt-8 scroll-mt-24 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Guided pathways</p><div className="mt-8 grid gap-5">{pathways.map((pathway) => (<a key={pathway.title} href={withBasePath(pathway.href)} className="group rounded-[2rem] border border-neutral-200 bg-[#f7f4ee] p-6 transition hover:-translate-y-1 hover:bg-white hover:shadow-md"><div className="grid gap-7 lg:grid-cols-[0.75fr_1.25fr] lg:items-start"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#111111] px-3 py-1 text-xs font-black uppercase tracking-[0.16em] text-white">{pathway.number}</span><span className="rounded-full bg-white px-3 py-1 text-xs font-black uppercase tracking-[0.16em] text-neutral-600">{pathway.tag}</span></div><h2 className="mt-5 font-sans text-3xl font-black leading-tight tracking-[-0.04em]">{pathway.title}</h2><p className="mt-4 text-sm font-black text-neutral-700">{pathway.level}</p></div><div><p className="text-base leading-8 text-neutral-700">{pathway.description}</p><div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-neutral-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.22em] text-[#8b1116]">Includes</p><ul className="mt-4 space-y-3 text-sm leading-7 text-neutral-700">{pathway.details.map((detail) => <li key={detail}>• {detail}</li>)}</ul></div><div className="rounded-3xl border border-neutral-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.22em] text-[#8b1116]">You will learn to</p><ul className="mt-4 space-y-3 text-sm leading-7 text-neutral-700">{pathway.outcomes.map((outcome) => <li key={outcome}>• {outcome}</li>)}</ul></div></div><p className="mt-7 text-sm font-black text-[#8b1116]">{pathway.cta} →</p></div></div></a>))}</div></section>
<section className="mt-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Interactive learning preview</p><h2 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Learn statistics by moving, seeing and interpreting.</h2><div className="mt-8 grid gap-8"><NormalDistributionExplorer /><RegressionLineExplorer /><ConfidenceIntervalSimulator /></div></section>
<section className="mt-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Flagship resource guides</p><div className="mt-8 grid gap-3">{resourceHighlights.map((resource, index) => (<a key={resource.href} href={withBasePath(resource.href)} className="rounded-3xl border border-neutral-200 bg-[#f7f4ee] p-5 transition hover:-translate-y-1 hover:bg-white"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#8b1116]">Guide {index + 1}</p><h2 className="mt-2 font-sans text-xl font-black tracking-[-0.03em]">{resource.title}</h2></a>))}</div></section>
<section className="mt-8 rounded-[2rem] bg-[#111111] p-6 text-white shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/85">Need live guidance?</p><div className="mt-4 grid gap-8 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><h2 className="max-w-3xl font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Enquire for subject-wise live sessions.</h2><p className="mt-5 max-w-3xl text-base leading-8 text-white/90">Alongside structured pathways, students can enquire about live support in statistics, biostatistics, programming, data science, bioinformatics and dissertation analysis.</p></div><div className="grid gap-3"><a href={withBasePath("/courses#live-sessions")} className="rounded-full bg-white px-6 py-4 text-center text-sm font-black text-[#111111]">View live session subjects</a><a href={withBasePath("/contact")} className="rounded-full border border-white/15 bg-white/10 px-6 py-4 text-center text-sm font-black text-white">Submit an enquiry</a></div></div></section>
</section></main>); }
