const basePath = process.env.NODE_ENV === "production" ? "/my-acad-tutor" : "";
function withBasePath(href: string) { if (href === "/") return `${basePath}/`; if (href.startsWith("#") || href.startsWith("http") || href.startsWith("mailto:")) return href; const cleanHref = href.endsWith("/") ? href.slice(0, -1) : href; return `${basePath}${cleanHref}/`; }
const contactItems = [
  { label: "Email", value: "contact@myacademictutor.com", href: "mailto:contact@myacademictutor.com", note: "Best for support requests, course enquiries and research guidance." },
  { label: "LinkedIn", value: "My Academic Tutor", href: "https://www.linkedin.com/company/myacademictutor/", note: "Follow platform updates, learning resources and course announcements." },
  { label: "YouTube", value: "StatisticaHub", href: "https://www.youtube.com/@StatisticaHub", note: "Watch statistics, biostatistics and quantitative learning content." },
];
const requirements = ["Subject area", "University level or course/module", "Topic, method or concept", "Software required, if any", "Deadline or preferred support time", "Type of support needed"];
const enquiryTypes = [
  { title: "Course enquiry", text: "Ask about Statistics Foundation, Machine Learning in Biostatistics or future course access." },
  { title: "Academic support", text: "Request guidance with statistics, biostatistics, programming, data science or software." },
  { title: "Research project guidance", text: "Ask about study design, variables, analysis planning, interpretation or reporting." },
];
export default function ContactPage() { return (<main className="min-h-screen bg-[#f7f4ee] px-5 py-10 text-[#111111] md:px-8 md:py-20"><section className="mx-auto max-w-7xl"><a href={withBasePath("/")} className="text-sm font-bold text-[#8b1116] hover:text-[#5f0b0f]">← Back to homepage</a>
<section className="mt-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-10 lg:p-12"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Contact</p><div className="mt-5 grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-end"><div><h1 className="max-w-5xl font-sans text-4xl font-black leading-[1.02] tracking-[-0.055em] sm:text-5xl md:text-7xl">Tell us what you need support with.</h1><p className="mt-6 max-w-4xl text-base leading-8 text-neutral-700 md:text-lg md:leading-9">Share your subject, academic level, topic, software requirements and deadline. We will suggest the most suitable support route.</p></div><div className="rounded-[1.75rem] border border-[#ead8d8] bg-[#f7f4ee] p-6"><p className="text-sm font-black uppercase tracking-[0.2em] text-[#8b1116]">Response preparation</p><h2 className="mt-4 font-sans text-2xl font-black tracking-[-0.04em]">Send a focused support request.</h2><p className="mt-4 text-sm leading-7 text-neutral-700">Include enough detail to understand your academic need, but do not send passwords, confidential data, exam material or restricted assessed work.</p></div></div></section>
<section className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="grid gap-4">{contactItems.map((item) => (<a key={item.label} href={item.href} target={item.href.startsWith("http") ? "_blank" : undefined} rel={item.href.startsWith("http") ? "noreferrer" : undefined} className="rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><p className="text-sm font-black uppercase tracking-[0.22em] text-neutral-700">{item.label}</p><p className="mt-3 font-sans text-2xl font-black tracking-[-0.035em] text-[#8b1116]">{item.value}</p><p className="mt-4 text-sm leading-7 text-neutral-700">{item.note}</p><p className="mt-5 text-sm font-black text-[#111111]">Open →</p></a>))}</div><article className="rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">What to include</p><h2 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Send a clear support request.</h2><div className="mt-6 grid gap-3">{requirements.map((item) => (<div key={item} className="rounded-2xl border border-neutral-200 bg-[#f7f4ee] px-4 py-3 text-sm font-bold leading-6 text-neutral-800">{item}</div>))}</div><a href="mailto:contact@myacademictutor.com?subject=Academic%20support%20request" className="mt-8 inline-flex w-full items-center justify-center rounded-full bg-[#111111] px-6 py-4 text-sm font-black text-white">Email support request →</a></article></section>
<section className="mt-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Enquiry types</p><div className="mt-8 grid gap-4 md:grid-cols-3">{enquiryTypes.map((item, index) => (<article key={item.title} className="rounded-[2rem] border border-neutral-200 bg-[#f7f4ee] p-6"><p className="font-sans text-3xl font-black tracking-[-0.05em] text-[#8b1116]">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-4 font-sans text-2xl font-black tracking-[-0.04em]">{item.title}</h2><p className="mt-4 text-sm leading-7 text-neutral-700">{item.text}</p></article>))}</div></section>
<section className="mt-8 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><article className="rounded-[2rem] border border-neutral-200 bg-[#111111] p-6 text-white shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/85">Academic integrity</p><h2 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Please ask for guidance, not replacement work.</h2><p className="mt-5 text-base leading-8 text-white/90">We support understanding, planning, interpretation and independent learning. We do not complete assessed work, exams or submissions.</p><a href={withBasePath("/academic-integrity")} className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-[#111111]">Read academic integrity policy →</a></article><article className="rounded-[2rem] border border-neutral-200 bg-[#8b1116] p-6 text-white shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/90">Quick email template</p><h2 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Copy this structure.</h2><div className="mt-5 rounded-3xl bg-white/10 p-5 text-sm leading-7 text-white/85"><p>Subject: Academic support request</p><p className="mt-3">My subject is...</p><p>My academic level is...</p><p>The topic/method I need help with is...</p><p>The software involved is...</p><p>My deadline/preferred support time is...</p></div><a href="mailto:contact@myacademictutor.com?subject=Academic%20support%20request" className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-[#111111]">Start email →</a></article></section>
</section></main>); }
