const basePath = "";
function withBasePath(href: string) { if (href === "/") return `${basePath}/`; if (href.startsWith("#") || href.startsWith("http") || href.startsWith("mailto:")) return href; const cleanHref = href.endsWith("/") ? href.slice(0, -1) : href; return `${basePath}${cleanHref}/`; }
const steps = [
  { title: "Share your topic", text: "Send your subject, level, topic, software and deadline so the support need is clear." },
  { title: "Clarify the goal", text: "The focus is shaped around explanation, method understanding, interpretation or planning." },
  { title: "Learn responsibly", text: "Support helps you understand and work independently while respecting academic integrity." },
];
const boundaries = ["No ghostwriting", "No exam impersonation", "No dishonest completion", "No forced conclusions"];
export default function HowSupportWorks() { return (<section className="bg-[#f7f4ee] px-5 py-10 text-[#111111] md:px-8 md:py-16"><div className="mx-auto max-w-7xl"><section className="rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-10"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">How support works</p><div className="mt-4 grid gap-6 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><h2 className="font-sans text-3xl font-black tracking-[-0.04em] md:text-5xl">A clear process for responsible academic guidance.</h2><p className="text-base leading-8 text-neutral-700">The process is designed to keep support focused, useful and academically responsible.</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{steps.map((step, index) => (<article key={step.title} className="rounded-[2rem] border border-neutral-200 bg-[#f7f4ee] p-6"><p className="font-sans text-3xl font-black tracking-[-0.05em] text-[#8b1116]">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-4 font-sans text-2xl font-black tracking-[-0.04em]">{step.title}</h3><p className="mt-4 text-sm leading-7 text-neutral-700">{step.text}</p></article>))}</div><section className="mt-8 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><article className="rounded-[2rem] border border-neutral-200 bg-[#111111] p-6 text-white shadow-sm"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/85">Clear boundaries</p><h3 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em]">Support explains and guides. It does not replace your work.</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{boundaries.map((item) => <div key={item} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-bold text-white/85">{item}</div>)}</div></article><article className="rounded-[2rem] border border-neutral-200 bg-[#8b1116] p-6 text-white shadow-sm"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/90">Ready to ask?</p><h3 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em]">Send a focused support request.</h3><p className="mt-5 text-base leading-8 text-white/80">Include the topic, academic level, deadline and the exact kind of help you need.</p><a href={withBasePath("/contact")} className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-[#111111]">Contact support →</a></article></section></section></div></section>); }
