const basePath = process.env.NODE_ENV === "production" ? "/my-acad-tutor" : "";
function withBasePath(href: string) { if (href === "/") return `${basePath}/`; if (href.startsWith("#") || href.startsWith("http") || href.startsWith("mailto:")) return href; const cleanHref = href.endsWith("/") ? href.slice(0, -1) : href; return `${basePath}${cleanHref}/`; }
const subjects = [
  { number: "01", title: "Statistics", description: "Support with probability, descriptive statistics, inference, regression and interpretation.", points: ["Probability", "Inference", "Regression"] },
  { number: "02", title: "Biostatistics", description: "Health-data support covering epidemiology, survival analysis and clinical research methods.", points: ["Survival", "Clinical trials", "Epidemiology"] },
  { number: "03", title: "Programming", description: "Guidance with R, Python, SPSS, SAS and Stata for academic analysis workflows.", points: ["R", "Python", "SPSS/SAS/Stata"] },
  { number: "04", title: "Research methods", description: "Support for research questions, variables, study design, analysis plans and reporting.", points: ["Design", "Variables", "Reporting"] },
  { number: "05", title: "Machine learning", description: "Prediction modelling, validation, metrics, overfitting and responsible interpretation.", points: ["Validation", "Metrics", "Prediction"] },
  { number: "06", title: "Bioinformatics", description: "Omics, gene expression, biological data workflows and interpretation support.", points: ["RNA-seq", "Omics", "Workflows"] },
];
const supportModes = ["Concept explanation", "Revision support", "Software walkthrough", "Method selection", "Research planning", "Interpretation guidance"];
export default function SubjectAreas() { return (<section className="bg-[#f7f4ee] px-5 py-10 text-[#111111] md:px-8 md:py-16"><div className="mx-auto max-w-7xl"><section className="rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-10"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Subject areas</p><div className="mt-4 grid gap-6 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><h2 className="font-sans text-3xl font-black tracking-[-0.04em] md:text-5xl">Support across quantitative academic subjects.</h2><p className="text-base leading-8 text-neutral-700">Subject support is designed around explanation, structure, interpretation and responsible academic guidance.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{subjects.map((subject) => (<article key={subject.title} className="rounded-[2rem] border border-neutral-200 bg-[#f7f4ee] p-6"><p className="font-sans text-4xl font-black tracking-[-0.05em] text-[#8b1116]">{subject.number}</p><h3 className="mt-4 font-sans text-2xl font-black tracking-[-0.04em]">{subject.title}</h3><p className="mt-4 text-sm leading-7 text-neutral-700">{subject.description}</p><div className="mt-5 flex flex-wrap gap-2">{subject.points.map((point) => (<span key={point} className="rounded-full border border-neutral-200 bg-white px-3 py-1 text-xs font-black uppercase tracking-[0.16em] text-neutral-600">{point}</span>))}</div></article>))}</div><section className="mt-8 grid gap-6 lg:grid-cols-[0.95fr_1.05fr]"><article className="rounded-[2rem] border border-neutral-200 bg-[#111111] p-6 text-white shadow-sm"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/85">Academic integrity first</p><h3 className="mt-4 font-sans text-3xl font-black leading-tight tracking-[-0.04em]">Support is designed to help students understand, not outsource.</h3><p className="mt-5 text-base leading-8 text-white/90">Sessions can support explanation, software guidance, analysis planning and interpretation. They are not used for ghostwriting or misconduct.</p><a href={withBasePath("/academic-integrity")} className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-[#111111]">Read academic integrity →</a></article><article className="rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Support modes</p><h3 className="mt-4 font-sans text-3xl font-black leading-tight tracking-[-0.04em]">Guidance can be adapted to your level and goal.</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{supportModes.map((mode) => (<div key={mode} className="rounded-2xl border border-neutral-200 bg-[#f7f4ee] px-4 py-3 text-sm font-bold text-neutral-800">{mode}</div>))}</div></article></section></section></div></section>); }
