const basePath = process.env.NODE_ENV === "production" ? "/my-acad-tutor" : "";
function withBasePath(href: string) { if (href === "/") return `${basePath}/`; if (href.startsWith("#") || href.startsWith("http") || href.startsWith("mailto:")) return href; const cleanHref = href.endsWith("/") ? href.slice(0, -1) : href; return `${basePath}${cleanHref}/`; }
const tiers = [
  { name: "Free", badge: "Start learning", price: "£0", period: "public access", summary: "Public learning materials for students exploring statistics, biostatistics, data science and research methods.", features: ["Learning Hub", "Selected previews", "Free guides", "Interactive demos", "Pathway guidance", "Integrity guidance"], cta: "Start free", href: "/learning-hub", highlighted: false },
  { name: "Premium Courses", badge: "Planned", price: "Coming soon", period: "course access", summary: "Structured course access for students who want complete learning pathways with lessons, labs and quizzes.", features: ["Full course access", "Detailed notes", "Worked examples", "Interactive labs", "Downloadable materials", "Certificate pathway"], cta: "Register interest", href: "/contact", highlighted: true },
  { name: "1-to-1 Academic Support", badge: "Guidance-based", price: "Request quote", period: "personal support", summary: "Personal academic support for statistics, biostatistics, programming, research methods and interpretation.", features: ["Tutoring", "Research guidance", "Software support", "Method support", "Revision help", "Responsible guidance"], cta: "Request support", href: "/contact", highlighted: false },
];
const notes = ["Payments are not live yet", "Support is quoted individually", "Academic integrity comes first"];
export default function PricingPage() { return (<main className="min-h-screen bg-[#f7f4ee] px-5 py-10 text-[#111111] md:px-8 md:py-20"><section className="mx-auto max-w-7xl"><a href={withBasePath("/")} className="text-sm font-bold text-[#8b1116] hover:text-[#5f0b0f]">← Back to homepage</a>
<section className="mt-8 rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm md:p-10 lg:p-12"><p className="text-sm font-black uppercase tracking-[0.22em] text-[#8b1116]">Pricing</p><div className="mt-5 grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-end"><div><h1 className="max-w-5xl font-sans text-4xl font-black leading-[1.02] tracking-[-0.055em] sm:text-5xl md:text-7xl">Simple pricing preview for courses and academic support.</h1><p className="mt-6 max-w-4xl text-base leading-8 text-neutral-700 md:text-lg md:leading-9">Payments are not live yet. This page shows the planned structure: free access, premium course access and personal support.</p></div><div className="rounded-[1.75rem] border border-[#ead8d8] bg-[#f7f4ee] p-6"><p className="text-sm font-black uppercase tracking-[0.2em] text-[#8b1116]">Current status</p><h2 className="mt-4 font-sans text-2xl font-black tracking-[-0.04em]">Pricing is currently a preview.</h2><p className="mt-4 text-sm leading-7 text-neutral-700">Course payments, subscriptions and paid access can be added later. Students can currently use free resources and enquire through contact.</p></div></div></section>
<section className="mt-8 grid gap-5 lg:grid-cols-3">{tiers.map((tier) => (<article key={tier.name} className={`rounded-[2rem] border p-6 shadow-sm md:p-7 ${tier.highlighted ? "border-[#8b1116] bg-[#111111] text-white" : "border-neutral-200 bg-white text-[#111111]"}`}><span className={`rounded-full px-3 py-1 text-xs font-black uppercase tracking-[0.18em] ${tier.highlighted ? "bg-white text-[#111111]" : "bg-[#f7f4ee] text-[#8b1116]"}`}>{tier.badge}</span><h2 className="mt-5 font-sans text-3xl font-black tracking-[-0.04em]">{tier.name}</h2><p className="mt-5 font-sans text-4xl font-black tracking-[-0.05em]">{tier.price}</p><p className={`mt-2 text-sm font-bold ${tier.highlighted ? "text-white/85" : "text-neutral-700"}`}>{tier.period}</p><p className={`mt-5 text-sm leading-7 ${tier.highlighted ? "text-white/90" : "text-neutral-700"}`}>{tier.summary}</p><div className="mt-6 grid gap-2">{tier.features.map((feature) => (<div key={feature} className={`rounded-2xl border px-4 py-3 text-sm font-bold leading-6 ${tier.highlighted ? "border-white/10 bg-white/5 text-white/85" : "border-neutral-200 bg-[#f7f4ee] text-neutral-700"}`}>{feature}</div>))}</div><a href={withBasePath(tier.href)} className={`mt-7 inline-flex w-full items-center justify-center rounded-full px-6 py-4 text-sm font-black ${tier.highlighted ? "bg-white text-[#111111]" : "bg-[#111111] text-white"}`}>{tier.cta} →</a></article>))}</section>
<section className="mt-8 grid gap-4 md:grid-cols-3">{notes.map((note) => (<article key={note} className="rounded-[2rem] border border-neutral-200 bg-white p-6 shadow-sm"><h2 className="font-sans text-2xl font-black tracking-[-0.04em]">{note}</h2><p className="mt-4 text-sm leading-7 text-neutral-700">This point should remain clear before any payment, course access or support booking is launched.</p></article>))}</section>
<section className="mt-8 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]"><article className="rounded-[2rem] border border-neutral-200 bg-[#111111] p-6 text-white shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/85">Want course access later?</p><h2 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Register interest for premium course release.</h2><p className="mt-5 text-base leading-8 text-white/90">Premium course access can be launched later with full lessons, labs, quizzes and downloadable materials.</p><a href={withBasePath("/contact")} className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-[#111111]">Register interest →</a></article><article className="rounded-[2rem] border border-neutral-200 bg-[#8b1116] p-6 text-white shadow-sm md:p-8"><p className="text-sm font-black uppercase tracking-[0.22em] text-white/90">Need personal support?</p><h2 className="mt-4 font-sans text-3xl font-black tracking-[-0.04em] md:text-4xl">Request a support quote.</h2><p className="mt-5 text-base leading-8 text-white/80">Send your subject, level, topic, software, deadline and type of support needed.</p><a href={withBasePath("/contact")} className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-[#111111]">Request support →</a></article></section>
</section></main>); }
